#!/Perl/bin/perl


print<<EOF;

<H2><FONT color=red><BR><BR><BR><BR><BR><HR>
<a target=chart href=http:/chart.bigcharts.com/bc3/intchart/frames/chart.asp?symb=SWINX&compidx=SP500%3A3377&comp=DJIA&ma=1&maval=9&uf=8&lf=1&lf2=65536&lf3=1&type=2&size=2&state=13&sid=11078&style=320&time=6&freq=1&nosettings=1&rand=774>  $i</a></font><BR> echo "<img src=http://chart.yahoo.com/c/3ms/s/$i.gif>
<img src=http://chart.yahoo.com/c/3mm/s/$i.gif><BR><BR></H2></font>

EOF

