#!/bin/sh

indexes="
SWCGX
SWHGX
SWPIX
SWPPX
SWBDX
SWITX
SWSMX
SWSSX
SWLBX
SWTIX
SWTSX
SWYPX
SWYSX
"


indexes="
swanx
swcgx
swhgx
swpix
swppx
swbdx
switx
swsmx
swssx
swlbx
swtix
swtsx
swypx
swysx
"

rawindexes="
snxfx
snxsx
swanx
swcax
swcsx
swinx
swisx
swntx
swobx
swogx
swoix
swosx
swegx
swbgx
swcgx
swhgx
swpix
swspx
swbdx
switx
swsmx
swssx
swlbx
swtix
swtsx
swypx
swyxs
"

raw_free_indexes="
swoix
swanx
swpix
"

free_indexes=`for i in $rawindexes
do
echo $i
done | sort `

indexes=`for i in $rawindexes
do
echo $i
done | sort `


echo "<!doctype html public \"-//w3c//dtd html 4.0 transitional//en\">
<html>
<head>
   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">
   <meta name=\"Author\" content=\"John van Vlaanderen\">
   <meta name=\"GENERATOR\" content=\"Mozilla/4.7 [en]C-CCK-MCD NSCPCD47  (WinNT; I) [Netscape]\">
   <title>Charts</title>
</head>
<body>
"

for i in $no_indexes
do

echo "<H2><FONT color=red><BR><BR><BR><BR><BR><HR> $i</font><BR>"
echo "<img src=http://chart.yahoo.com/c/3ms/s/$i.gif>"
echo "<img src=http://chart.yahoo.com/c/3mm/s/$i.gif><BR><BR></H2></font>"


done

for i in $free_indexes
do

echo "<H2><FONT color=red><BR><BR><BR><BR><BR><HR> $i</font><BR>"
echo "<img src=http://chart.yahoo.com/c/3ms/s/$i.gif>"
echo "<img src=http://chart.yahoo.com/c/3mm/s/$i.gif><BR><BR></H2></font>"
echo "<a target=new src=http://chart.bigcharts.com/bc3/intchart/frames/chart.asp?symb=SWINX&compidx=SP500%3A3377&comp=DJIA&ma=1&maval=9&uf=8&lf=1&lf2=65536&lf3=1&type=2&size=2&state=13&sid=11078&style=320&time=6&freq=1&nosettings=1&rand=774> $i </a>"

done


for i in $indexesno
do

echo "<font +5><BR><BR><BR><BR><BR> $i </font><BR>


<img src=\"http://chart.bigcharts.com/bc3/intchart/frames/chart.asp?symb=$i&compidx=SP500%3A3377&comp=DJIA&ma=0&maval=9&uf=0&lf=1&lf2=0&lf3=0&type=2&size=2&state=13&sid=18167&style=320&time=5&freq=1&nosettings=1&rand=246\">"

done 

echo "</body> </html>"
